name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly-2025-01-01
        target: x86_64-unknown-none
    - name: Build
      run: make
    - uses: actions/upload-artifact@v4
      with:
        name: DoglinkOS.iso
        path: DoglinkOS-x86_64.iso

